spring:
    datasource:
        username: lionel
        url: jdbc:mysql://localhost:3306/chat
        password: Mmh28803#
    jpa:
        show-sql: false
        hibernate:
             ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
server:
    port: 8000